workflows:
  version: 2
  test:
    jobs:
      - test
version: 2
jobs:
  test:
    environment:
      FLM_ENV: "test"
    docker:
      - image: circleci/python:3-stretch-node-browsers
    steps:
      - run:
          name: Verify python versions
          command: |
            python --version
            python3 --version
            pip --version
      - run: sudo apt install gnupg2 python3-pyqt5 tor
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -q --upgrade pip
            pip install -q -r ./requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py pytest
